apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zooanimals
  template:
    metadata:
      labels:
        app: zooanimals
    spec:
      containers:
      - name: zooanimals
        image: nkrupchak/zooanimals:latest
---
apiVersion: v1
kind: Service
metadata:
  name: animals-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: zooanimals
  ports:
    - name: zooanimals
      protocol: TCP
      port: 80
      targetPort: 80
    - name: zooanimalsgrpc
      protocol: TCP
      port: 666
      targetPort: 666